---
- name: Setup DBServer
  hosts: db
  become: yes
  tasks:
    - name: Install MySQL server
      yum:
        name: mariadb-server
        state: present
    - name: Start & Enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Install python mysql
      yum:
        name: MySQL-python
        state: present
    - name: Create database named accounts
      mysql_db:
        name: accounts
        state: present
    - name: Add user to database
      mysql_user:
        name: devops
        password: 12345
        priv: '*.*:ALL'
        state: present
