---
- name: Understanding precedence of variables
  hosts: all
  become: yes
  vars:
    usrnm: playuser
    commnt: 'variable from playbook'
  tasks:
    - name: create user
      user:
        name: "{{ usrnm  }}"
        comment: "{{ commnt  }}"
      register: usrout

    - debug:
        var: usrout.name

    - debug:
        var: usrout.comment
        
