---
- name: Setup WebServer
  hosts: web
  become: yes
  tasks:
    - name: Install Apache httpd
      yum:
        name: httpd
        state: present
    - name: Start & Enabled httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Copy index.html to httpd
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
        backup: yes
- name: Setup DBServer
  hosts: db
  become: yes
  tasks:
    - name: Install MySQL server
      yum:
        name: mariadb-server
        state: present
    - name: Start & Enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
