---
- name: Learning ansible facts
  hosts: all
  tasks:
      - name: Print OS name
        debug:
          var: ansible_distribution
      - name: Print memory details
        debug:
          var: ansible_memory_mb.real.free
      - name: Print machine processor
        debug:
          var: ansible_processor[2]
