---
- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP on Centos
      yum:
        name: "{{ item }}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP on Ubuntu
      apt:
        name: "{{ item }}"
        update_cache: true
        state: present
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start & enabledd NTP on RedHat
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start & enable NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Add group
      group:
        name: devops
        state: present

    - name: add users
      user:
        name: "{{ item }}"
        state: present
        groups: devops
      loop: "{{ usernames }}"
